version: "1.0"
services:
  web:
    build: .
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - "./configuration.json:/configuration_docker.json"
      - "./reverse_proxy.com+3.pem:/reverse_proxy.com+3.pem"
      - "./reverse_proxy.com+3-key.pem:/reverse_proxy.com+3-key.pem"
      - "./log_file.log:/log_file.log"

    # depends_on:
    #   test_server:
    #     condition: service_started

  testserver:
    image: "kennethreitz/httpbin"
    ports:
      - "8080:80"
