services:
  web:
    build: .
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - "./configuration_docker.json:/configuration.json"
      - "./reverse_proxy.com+3.pem:/reverse_proxy.com+3.pem"
      - "./reverse_proxy.com+3-key.pem:/reverse_proxy.com+3-key.pem"
      - "./log_file.log:/log_file.log"

  testserver:
    image: "kennethreitz/httpbin"
    ports:
      - "8080:80"
